fixtures:
  repositories:
      stdlib:
        repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
        branch: "3.2.0"
      archive:
        repo:   "https://github.com/puppet-community/puppet-archive.git"
        branch: "0.3.0"
  symlinks:
    'wildfly': '#{source_dir}'